# This file contains all available configuration options
# with their default values.

version: "2"

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4
  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - e2e
  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  modules-download-mode: vendor
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # include test files or not, default is true
  tests: true
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false
# output configuration options
output:
  formats:
    tab:
      path: stdout
      # print linter name in the end of issue text, default is true
      print-linter-name: true
  # add a prefix to the output file references; default is no prefix
  path-prefix: ""
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # make issues output unique by line
  uniq-by-line: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      # put imports beginning with prefix after 3rd-party packages;
      # it's a comma-separated list of prefixes
      local-prefixes:
        - github.com/openshift/external-dns-operator
  exclusions:
    # enables skipping of directories:
    # vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
