apiVersion: externaldns.olm.openshift.io/v1alpha1
kind: ExternalDNS
metadata:
  name: sample-gcp
spec:
  domains:
  - filterType: Include
    matchType: Exact
    name: test-gcp1.qe.gcp.devcluster.openshift.com
  provider:
    type: GCP
  source:
    # In case you have multiple ingress controllers you must specify ingress controller name in the routerName
    # so that the external dns will use the router canonical name correrponding to it to create a dns record. 
    openshiftRouteOptions:  
      routerName: default
    # Source Type is route resource of OpenShift    
    type: OpenShiftRoute
    # It's not possible to not have FQDNTemplate if the hostname annotation policy is ignore.
    fqdnTemplate: 
    - "{{.Name}}.apps.test-gcp1.qe.gcp.devcluster.openshift.com"
  zones:
  - test-gcp1-q6m5v-private-zone
