apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-dns-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-dns-operator
subjects:
  - kind: ServiceAccount
    name: external-dns-operator
