apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: external-dns
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: external-dns-operator-operand
  namespace: external-dns
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-dns-operator-operand
  namespace: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-dns-operator-operand
subjects:
- kind: ServiceAccount
  name:  external-dns-operator
  namespace:  external-dns-operator